# Generated by Django 5.2.9 on 2025-12-25 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='users-avatars', verbose_name='Аватар'),
        ),
    ]
